cc_library(
    name = "singly-linked-list",
    srcs = ["SinglyLinkedList.h"],
    hdrs = ["SinglyLinkedList.cpp"],
    visibility = ["//visibility:public"],
)

cc_library(
    name = "static-linked-list",
    srcs = ["StaticLinkedList.h"],
    hdrs = ["StaticLinkedList.cpp"],
    visibility = ["//visibility:public"],
)